ORDER_IN_FEED = "//a[contains(@class, 'OrderHistory_link')]"
MODAL_ORDER_DETAILS = "//div[contains(@class, 'Modal_orderBox')]"
MODAL_WINDOW_CLOSE = "//button[contains(@class, 'Modal_modal__close')]"
TEXT_ORDER_ID = "//p[contains(@class, 'text_type_digits-default')]"
COUNTER_ALL_TIME = "//p[contains(@class, 'OrderFeed_number') and preceding-sibling::p[text()='Выполнено за всё время:']]"
COUNTER_TODAY = "//p[contains(@class, 'OrderFeed_number') and preceding-sibling::p[text()='Выполнено за сегодня:']]"
ORDER_IN_WORK = "//ul[contains(@class, 'OrderFeed_orderListReady')]//li"
ORDER_NUMBER = "//*[contains(text(), '{}')]"
ORDER_FEED_NUMBER = "//p[contains(@class, 'OrderFeed_number')]"
ORDER_LAST_NUMBER = "//p[contains(@class, 'text_type_digits-default')]"
